# Generated by Django 4.0.6 on 2022-09-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_seatreservationstatus_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='seatreservationstatus',
            name='token',
            field=models.CharField(default=None, max_length=600, null=True),
        ),
    ]
