# Generated by Django 4.0.6 on 2022-09-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seatreservationstatus',
            name='bus',
        ),
    ]
