# Generated by Django 4.0.6 on 2022-08-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('otp', models.CharField(blank=True, max_length=4, null=True)),
                ('count', models.IntegerField(default=0, help_text='Number of OTPs sent')),
                ('validated', models.BooleanField(default=False)),
            ],
        ),
    ]
