# Generated by Django 4.0.6 on 2022-09-02 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_bus_fee_alter_bus_number_alter_bus_seats'),
        ('accounts', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buses.bus'),
        ),
    ]
