# Generated by Django 4.0.6 on 2022-08-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField()),
                ('plate_number', models.CharField(default=0, max_length=255)),
                ('seats', models.PositiveBigIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Buses',
            },
        ),
    ]
