# Generated by Django 4.0.6 on 2022-08-06 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name_plural': 'Buses'},
        ),
        migrations.AddField(
            model_name='bus',
            name='plate_number',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='bus',
            name='current_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buses.driver'),
        ),
    ]
