# Generated by Django 4.0.6 on 2022-09-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_bus_destination_bus_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bus',
            name='number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='seats',
            field=models.PositiveIntegerField(),
        ),
    ]
